import Head from "next/head";
import { FC } from "react";
import { NavBar } from "../NavBar";
import styles from "./MainLayout.module.css";

interface Props {
  children: React.ReactNode;
}


export const MainLayout:FC<Props> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>About Antonia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>{children}</main>
    </div>
  );
};
